//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ConnectionLibs : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionLibs defaultInstance = ((ConnectionLibs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionLibs())));
        
        public static ConnectionLibs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TCPConnections.dll")]
        public string TCP {
            get {
                return ((string)(this["TCP"]));
            }
            set {
                this["TCP"] = value;
            }
        }
    }
}
